### ISSUE TITLE
求教PYLEN是拼音或者字形序列的最大长度吗？谢谢

### ISSUE THREAD

**Issue by Arthassssss** [liushulinle/PLOME#11]
拼音强制指定为了4，但是汉字的拼音有很多长度会超过4的。
字形的，为什么要这样判定呢：
`if len(self.ZM2ID) < 10:
    self.PYLEN = 10
else:
    self.PYLEN = 5`

**Comment by liushulinle** [comment]
1） 拼音长度的超参数没有详细调，设置更大值可能会更好。
2）这个是我做其它实验写的，忘记改了，在这个工作中，由于len(ZM2ID) < 10 (不同笔画数），因此只会赋值10
