### ISSUE TITLE
预训练的数据问题

### ISSUE THREAD

**Issue by Yang-HangWA** [liushulinle/PLOME#14]
你好，我注意到论文中写到预训练中数据有162.1百万的句子，可以把这部分数据开放出来么，因为其中提到还有部分数据是从中文新闻平台获取，这部分数据并不可知。

**Comment by liushulinle** [comment]
业务数据不方便放出来。我们验证过，预训练语料只用百科数据效果基本没有太大差异。

**Comment by Yang-HangWA** [comment]
@liushulinle 那这部分的分句是怎么做的呢，因为我看到论文中提到分句这个操作，而项目中给出的pretrain_corpus_examples.txt数据集并不能看出分句是如何操作的。

**Comment by liushulinle** [comment]
基于标点符号进行的分句，这个策略对整体的影响应该不大，大概总结一些句子分隔符号进行分隔即可。分的时候，保证句子长度不超过512.
