### ISSUE TITLE
finetue后离论文差距较大？

### ISSUE THREAD

**Issue by mosthandsomeman** [liushulinle/PLOME#15]
作者您好，我使用您在github上pretrain的模型，并用其中的train.txt做finetue, 在sighan2015(1100条数据，541个错误句子，703错误字)上各项指标离论文中的指标有较大差距，请问可能是哪里出错了吗？

**Comment by mosthandsomeman** [comment]
只改了batchszie,其他都没改

**Comment by Johnson-NLP** [comment]
@mosthandsomeman 老哥，我改了max_sen_len，跑出来比他论文里还高。。。你是低很多吗？我看论文里写的是跑4次取平均

**Comment by Johnson-NLP** [comment]
讲道理max_sen_len和batchsize都按原代码不改的话16G显存也会爆

**Comment by mosthandsomeman** [comment]
就是跑不动，才把batchsize改小， 在项目里给的test.txt上跑的指标也不行。Johnson-NLP，你训了多少epoch?

**Comment by mosthandsomeman** [comment]
sighan2015测试集上有1100的样本，541个错句子，703出错误，和论文中说的461处错误不一样，观察后发现sighan本身质量不高，不知道作者有没有手动对其进行调整?

**Comment by Johnson-NLP** [comment]
> 就是跑不动，才把batchsize改小， 在项目里给的test.txt上跑的指标也不行。Johnson-NLP，你训了多少epoch?

10个epoch

**Comment by mosthandsomeman** [comment]
谢谢老哥，回头我再试一下能不能复现

**Comment by Yang-HangWA** [comment]
@Johnson-NLP 你跑的指标大概啥样，我跑的也和论文里的不一样，看似更高。。

**Comment by mosthandsomeman** [comment]
@Yang-HangWA， 下载的预训练模型里有个test.txt, 里面都是错误样本，在这上面我测试的比论文中table2各项指标平均低5%；自己下载的sighan2015,里面1100的样本，541个错句子，703出错误，和论文中说的461处错误不一样，比论文中table3各项指标平均低很多，甚至达到20%以上； 不知道你们用什么测试集？

**Comment by Yang-HangWA** [comment]
就是下载的test.txt，你说的各项指标是咋样的。我看代码里其实就是把test.txt当成了验证集，然后每轮出验证集上的结果，你是划分训练数据训练然后单独测试了这个么。我这边还得再测试看看，先重新跑一轮看看。

**Comment by mosthandsomeman** [comment]
指标也是论文代码里面的score_f, 和score_f_sent，这两个函数也没啥问题。用这个放进去做验证集，我这边确实也会收敛到很高的指标。我是把train.txt281381条数据，切了训练集，验证集，测试集，验证集一千，测试集2万。https://github.com/onebula/sighan_raw在这上面找的测试集，但是错误数量和论文里面不一样，句子质量看起来比较低

**Comment by Junshuai-Song** [comment]
> 

你好，请问你改max_sen_len，是重新预训练了模型吗？

我直接改为论文中的180，会报如下错误：
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: stroke_ids.  Can't parse serialized Example.`

**Comment by mosthandsomeman** [comment]
作者您好，能否上传一下您所用的大小为1100的测试集?

**Comment by Junshuai-Song** [comment]
pinyin result:
token check: p=1.000, r=1.000, f=1.000
token correction: p=1.000, r=1.000, f=1.000
fusion result:
token check: p=1.000, r=1.000, f=1.000
token correction: p=1.000, r=1.000, f=1.000
sent check: p=1.000, r=1.000, f=1.000
sent correction: p=0.994, r=0.994, f=0.994
best f value: 0.9999999790728814

**Comment by mosthandsomeman** [comment]
@Junshuai-Song，我训练完在dev也没达到这么高

**Comment by chinazoujy** [comment]
> 

确实，我的就报了OOM的错误

**Comment by liushulinle** [comment]
感谢楼上各位对我们工作的关注，用我们提供的训练好的模型直接在评测集上评估，是可以跑出论文结果的。评估脚本和代码在finetune_src/train_eval.py里面有，只是没有单独分离出来。需要的话可以自行分离出来的。

自己训练的话，请保证batch_size/max_sen_len等超参数和论文给出的相同。

**Comment by liushulinle** [comment]
https://github.com/liushulinle/CRACSpell/tree/main/datas/sighan 评测集在这里可以下载

**Comment by joyJZhang** [comment]
> 感谢楼上各位对我们工作的关注，用我们提供的训练好的模型直接在评测集上评估，是可以跑出论文结果的。评估脚本和代码在finetune_src/train_eval_tagging.py里面有，只是没有单独分离出来。需要的话可以自行分离出来的。
> 
> 自己训练的话，请保证batch_size/max_sen_len等超参数和论文给出的相同。

您好，训练好的模型是pretrained_plome 这个吗

**Comment by joyJZhang** [comment]
> 感谢楼上各位对我们工作的关注，用我们提供的训练好的模型直接在评测集上评估，是可以跑出论文结果的。评估脚本和代码在finetune_src/train_eval_tagging.py里面有，只是没有单独分离出来。需要的话可以自行分离出来的。
> 
> 自己训练的话，请保证batch_size/max_sen_len等超参数和论文给出的相同。

代码里训练中的验证集用的是测试数据集，最终得出在是测试表现最好的模型。这是CSC通用的微调评估方式吗，因为CSC任务重没有找到有公开的验证集
