### ISSUE TITLE
测试数据集及评价方式？

### ISSUE THREAD

**Issue by wangwang110** [liushulinle/PLOME#17]
感谢公开源码！

我使用放出的plome模型，使用放出的训练集微调，使用放出的测试集（542条），最后的结果是
`pinyin result:
token check: p=0.933, r=0.874, f=0.902
token correction: p=0.975, r=0.852, f=0.909
fusion result:
token check: p=0.936, r=0.871, f=0.902
token correction: p=0.966, r=0.841, f=0.899
sent check: p=0.867, r=0.800, f=0.832
sent correction: p=0.841, r=0.776, f=0.807
`
不知是否正确？

论文给出的结果为
![image](https://user-images.githubusercontent.com/21475557/157999331-00fe6d92-6e67-40d5-a86e-932e14806062.png)

不过测试集好像是1100条

这两个结果是同一种评价方式吗？

求解答

**Comment by wangwang110** [comment]
在1100条上的结果是：
`pinyin result:
token check: p=0.825, r=0.876, f=0.850
token correction: p=0.976, r=0.855, f=0.911
fusion result:
token check: p=0.831, r=0.873, f=0.851
token correction: p=0.967, r=0.844, f=0.901
sent check: p=0.761, r=0.803, f=0.782
sent correction: p=0.737, r=0.778, f=0.757`

**Comment by Zhouyuhao97** [comment]
您好，我把batchsize改成16之后和您的结果差不多，和论文表格中Character-level的结果差的不多，但是和Sentence-level差别有点大，请问您知道这是怎么回事了吗？

**Comment by wangwang110** [comment]
可能试试batchsize设置的问题吧

**Comment by wangwang110** [comment]
> 您好，我把batchsize改成16之后和您的结果差不多，和论文表格中Character-level的结果差的不多，但是和Sentence-level差别有点大，请问您知道这是怎么回事了吗？

大概还是batchsize设置的问题吧

**Comment by Zhouyuhao97** [comment]
> > 您好，我把batchsize改成16之后和您的结果差不多，和论文表格中Character-level的结果差的不多，但是和Sentence-level差别有点大，请问您知道这是怎么回事了吗？
> 
> 大概还是batchsize设置的问题吧

您后来能成功复现论文表格中的结果吗？

**Comment by wangwang110** [comment]
> 没有，上面的结果是batchsize=8的结果。你可以试试增大batchsize试试，显卡大小不够，可以采用梯度累积的方式。

**Comment by Zhouyuhao97** [comment]
好的，谢谢您。

**Comment by liushulinle** [comment]
![image](https://user-images.githubusercontent.com/5656506/158098479-7ce4c15b-744d-4639-b87d-540be88b5f6a.png)
由于前人在错别字任务上评价方式各不相同。为了可比性，这里遵循了前人的评价方式。这个表里，character级的评测是在550纯正例评测集评测的，sentence-level是在1100条全测试集评测的。

自己finetuning的话，batch_size和max_sen_len和论文保持一致，否则确实结果可能会有比较大的差异。

**Comment by liushulinle** [comment]
https://github.com/liushulinle/CRACSpell/tree/main/datas/sighan  评测集在这里可以下载
