### ISSUE TITLE
预训练模型相关

### ISSUE THREAD

**Issue by Zhouyuhao97** [liushulinle/PLOME#18]
作者您好，最近我想将预训练的模型迁移到pytorch上，请问gru相关的参数对模型性能有影响吗？没有影响的话只把bert的参数迁移过去会方便很多。

**Comment by Zhouyuhao97** [comment]
已找到解决方案，但模型权重中缺少拼音输出dense权重。
已完成复现，关闭issue。

**Comment by LuckyyySTA** [comment]
> 已找到解决方案，但模型权重中缺少拼音输出dense权重。 已完成复现，关闭issue。

您好，我用 PyTorch 复现的过程中出现了相同的问题，请问您最后是如何解决的呢？
