### ISSUE TITLE
微调数据存在错误

### ISSUE THREAD

**Issue by OKC13** [liushulinle/PLOME#5]
经检查，微调所用的数据，gold部分（\t分割的右半部分）也存在较多错误，并非全正确的句子。
如：
这 项 会 议 的 召 开 是 世 养 爱 滋 曰 活 动 之 一 。	这 项 会 议 的 召 开 是 世 界 爱 滋 日 活 动 之 一 。

**Comment by liushulinle** [comment]
错别字的数据集漏标比较严重，这个是数据集方面的问题。论文使用的finetuning数据来自公开数据，本文没有处理噪声问题。
