### ISSUE TITLE
InvalidArgumentError: Key: segment_ids. Can't parse serialized Example.

### ISSUE THREAD

**Issue by chizhu** [liushulinle/PLOME#9]
在finetune过程中，将max_seq_len从180改小成128，引发错误
InvalidArgumentError: Key: segment_ids. Can't parse serialized Example.

**Comment by liushulinle** [comment]
改完参数，要重新调用dataprocessor转tfrecord

**Comment by Junshuai-Song** [comment]
@liushulinle  你好  finetune过程不是不需要dataprocessor么？

pre_train过程这样解决了

**Comment by liushulinle** [comment]
finetuning和pretrain都需要dataprocessor的
